### ISSUE TITLE
Plain editor is too slow in Safari

### ISSUE THREAD

**Issue by yy** [akngs/ecogwiki#81]
The plain editor is not responsive enough and difficult to use in Safari. The Typed characters appear after some delay.

**Comment by akngs** [comment]
It should be fixed by now. Could you confirm it?

**Comment by yy** [comment]
I've updated with the latest version but the problem still seems to exist. When I type one character, say 'a', it sometimes takes a couple of seconds (or typing another key) until the character appear.

**Comment by akngs** [comment]
Could you send me navigator.userAgent string?
1. Open Developer Console
2. Type `navigator.userAgent`

**Comment by yy** [comment]
Sorry for not providing this info earlier. 

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11"

**Comment by akngs** [comment]
It's puzzling. Your UA string is exactly matched to that of mine.
1. Do you use any plugin or extensions?
2. When you use Plain mode, do you see plain `textarea` or CodeMirror editor which does syntax highlighting?

**Comment by yy** [comment]
The only extension is 1password 4. Another computer of mine has exactly the same setting, but doesn't have this issue. 

It's CodeMirror editor.

**Comment by yy** [comment]
This problem disappeared. Don't know exactly what was the problem. :/

**Comment by akngs** [comment]
Weird, but good to hear that :-)
